[
    "87. Nae iste magno conatu magnas nugas dixerit. 14583. 15 Quasi quidquam infelicius sit homini cui sua figmenta dominantur. 16",
    "193. Quid fiet hominibus qui minima contemnunt, majora non credunt? 24",
    "364. Rarum est enim ut satis se quisque vereatur. 58\nTot circa unum caput tumultuantes deos. 59\nNihil turpius quam cognitioni assertionem praecurrere. 60\nNec me pudet, ut istos, fateri nescire quid nesciam. 61\nMelius non incipient. 62",
    "776. Ne timeas pusillus grex. 168 Timore et tremore. 169 —Quid ergo? Ne timeas modo timeas. Fear not, provided you fear; but if you fear not, then fear.\n\nQui me recipit, non me recipit, sed eum qui me misit. 170\nNemo scit, neque Filius. 171\nNubes lucida obumbravit. 172\nSaint John was to turn the hearts of the fathers to the children, and Jesus Christ to plant division. There is not contradiction.\n",
    "842. Si tu es Christus, dic nobis. 193\nOpera quae ego facio in nomine patris mei, haec testimonium perhibent de me. Sed vos non creditis quia non estis ex ovibus meis. Oves meae vocem meam audiunt. 194\nJohn 6:30. Quod ergo tu facis signum ut videamus et credamus tibi? (Non dicunt: Quam doctrinam praedicas?) 195\nNemo potest facere signa quae tu facis nisi Deus. 196\nII Macc. 14:15. Deus qui signis evidentibus suam portionem protegit. 197\nVolumus signum videre de coelo, tentantes eum. 198 Luke 11:16.\n\nGeneratio prava signum quaerit; et non dabitur. 199\nEt ingemiscens ait: Quid generatio ista signum quaerit? 200 (Mark 8:12.) They asked a sign with an evil intention.\n\nEt non poterat facere. 201 And yet he promises them the sign of Jonah, the great and wonderful miracle of his resurrection.\n\nNisi videritis, non creditis. 202 He does not blame them for not believing unless there are miracles, but for not believing unless they are themselves spectators of them.\n\nAntichrist in signis mendacibus, 203 says Saint Paul, II Thess. 2.\n\nSecundum operationem Satanae, in seductione iis qui pereunt eo quod charitatem veritatis non receperunt ut salvi fierent, ideo mittet illis Deus optationes erroris ut credant mendacio. 204\nAs in the passage of Moses: Tentat enim vos Deus, utrum diligatis eum. 205\nEcce praedixi vobis: vos ergo videte. 206",
    "90. Quod crebro videt non miratur, etiamsi cur fiat nescit; quod ante non viderit, id si evenerit, ostentum esse censet. 17",
    "363. Ex senatus-consultis et plebiscitis scelera exercentur. Seneca. 588. 49\nNihil tam absurde dici potest quod non dicatur ab aliquo philosophorum. 50\nQuibusdam destinatis sententiis consecrati quae non probant coguntur defendere. 51\nUt omnium rerum sic litterarum quoque intemperantia laboramus. 52\nId maxime quemque decet, quod est cujusque suum maxime. 53\nHos natura modos primum dedit. 54\nPaucis opus est litteris ad bonam mentem. 55\nSi quando turpe non sit, tamen non est non turpe quum id a multitudine laudetur. 56\nMihi sic usus est, tibi ut opus est facto, fac. 57",
    "551. Dignior plagis quam osculis non timeo quia amo. 94",
    "696. Susceperunt verbum cum omni aviditate, scrutantes Scripturas, si ita se haberent. 138",
    "754. Homo existens te Deum facit. 149\nScriptum est, Dii estis, et non potest solvi Scriptura. 150\nHaec infirmitas non est ad vitam et est ad mortem. 151\nLazarus dormit, et deinde dixit: Lazarus mortuus est. 152",
    "890. Tertullian: Nunquam Ecclesia reformabitur. 222",
    "901. Humilibus dat gratiam; 223 an ideo non dedit humilitatem? 224\nSui eum non receperunt; quotquot autem non receperunt, 225 an non erant sui? 226",

]